version: "3.8"
services:
  vault:
    image: hashicorp/vault:1.14.2
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: "server -dev -dev-root-token-id=root-token"
    volumes:
      - ./vault-data:/vault/data

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      retries: 10

  mongo:
    image: mongo:6.0
    command: ["--bind_ip_all"]
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      retries: 10

  privatebin:
    image: privatebin/nginx-fpm-alpine:1.6.2
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    volumes:
      - ./privatebin-data:/srv/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 10s
      retries: 3

  buildkite-agent:
    image: buildkite/agent
    environment:
      BUILDKITE_AGENT_TOKEN: "dummy-token"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - vault
      - privatebin
      - mysql
      - mongo